# Generated by Django 5.2.1 on 2025-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='location_lon',
        ),
        migrations.AddField(
            model_name='answer',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
