# Generated by Django 5.2.1 on 2025-06-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0003_answer_is_admin_submission_answer_submitted_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
