# Generated by Django 5.2.1 on 2025-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0005_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
